### PR TITLE
Ensure we match types within selector

### LINKED ISSUE #34: Restricting methods with <package>.<type>.<method> doesn't work if return value is directly accessed
I'm using the linter to restrict the GORM Raw method. I run the linter with golangci-lint 1.53.2. The forbidigo configuration is:
```
  forbidigo:
    analyze-types: true
    forbid:
      - p: gorm.DB.Raw
        msg: Example message.
```

Running the linter on the following example code it recognizes the first two instances but not the last one:
```
	var db *gorm.DB
	_ = db.Raw("...")
	_ = db.Session(nil).Raw("...")
	_ = db.Raw("...").Error
```

### PR DESCRIPTION
**Pull request by ashanbrown**
Fixes #34 

The logs for this case produce:

>    forbidigo.go:282: /Users/andrew/Projects/forbidigo/pkg/analyzer/testdata/src/expandtext/expandtext.go:42:6: selector "c.AlsoForbidden().Value" with supported type "*example.com/some/pkg.Result": "c.AlsoForbidden().Value" -> "pkg.Result.Value", package "example.com/some/pkg"

### CODE REVIEW

File: forbidigo/forbidigo.go [hunk 1]
```diff
@@ -214,6 +214,14 @@ func (v *visitor) Visit(node ast.Node) ast.Visitor {
 			})
 		}
 	}
+
+	// descend into the left-side of selectors
+	if selector, isSelector := node.(*ast.SelectorExpr); isSelector {
```
Comment (pohly) [inline forbidigo/forbidigo.go:219]: This was also my first guess for why this wasn't caught before :smile:
